#-------------------------------
# first git action
# created by Dag
#-------------------------------
name: My-first-action

on:
  push:
    branches: 
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: aaa
      run: echo "HELLO TESTING"
    - name: sleep
      run: sleep 3

  testing-2:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
    - name: bbb
      run: echo "HELLO TESTING-2"
    
    - name: sleep_2
      run: sleep 3
      
