#-------------------------------
# first git action
# created by Dag
#-------------------------------
name: My-first-action
env:
  App_name: "First_app"
  Package_name: "first_app_version-${{ github.sha }}"
on:
  push:
    branches: 
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: aaa
      run: echo "HELLO TESTING"
    - name: sleep
      run: sleep 1
    - name: show dir
      run: ls -la
    - name: pwd
      run: pwd
      
  testing-2:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
    - name: bbb
      run: echo "HELLO TESTING-2"
    - name: sleep_2
      run: sleep 1
    - name: prnt
      run: echo "env.App_name   ===   env.Package_name"

      
